from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks" / "colab"
OUT.mkdir(parents=True, exist_ok=True)

# ============================================================
# Blocos reutilizáveis para todos os notebooks
# ============================================================

COMMON_SETUP = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# {TITLE}\n",
            "\n",
            "Este notebook foi gerado automaticamente para executar o experimento **{TITLE}**.\n",
            "\n",
            "## Objetivo\n",
            "Este notebook serve para:\n",
            "\n",
            "1. configurar o ambiente (local ou Colab),\n",
            "2. localizar corretamente a raiz do projeto,\n",
            "3. garantir acesso ao código em `src/`,\n",
            "4. opcionalmente montar o Google Drive e copiar dados,\n",
            "5. executar o treino do modelo,\n",
            "6. extrair histórico de treino,\n",
            "7. plotar gráficos de **Loss** e **AUC**,\n",
            "8. salvar resumos em `artifacts/colab_summaries/`.\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Etapa 1 — Detectar ambiente e localizar a raiz do projeto\n",
            "\n",
            "Nesta etapa, o notebook identifica se está rodando no **Google Colab** ou no **ambiente local**.\n",
            "\n",
            "### O que esta célula resolve\n",
            "- no Colab: clona automaticamente o repositório, instala dependências e usa `/content/ai-core`\n",
            "- no local: detecta corretamente a raiz do projeto mesmo se o notebook estiver sendo executado de dentro de `notebooks/colab/`\n",
            "- adiciona `src/` ao `sys.path`, evitando erros como `ModuleNotFoundError: brain_kt`\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from pathlib import Path\n",
            "import os\n",
            "import sys\n",
            "\n",
            "IN_COLAB = 'google.colab' in sys.modules\n",
            "REPO_URL = 'https://github.com/GuilhermeDesoler/ai-core.git'\n",
            "\n",
            "if IN_COLAB:\n",
            "    REPO_DIR = Path('/content/ai-core')\n",
            "    if not REPO_DIR.exists():\n",
            "        get_ipython().system(f'git clone -b improve/high-impact-training {REPO_URL} /content/ai-core')\n",
            "    get_ipython().run_line_magic('cd', '/content/ai-core')\n",
            "    get_ipython().system('pip install -q -r requirements.txt')\n",
            "else:\n",
            "    cwd = Path.cwd().resolve()\n",
            "\n",
            "    # Caso 1: notebook aberto em ai-core/notebooks/colab\n",
            "    if cwd.name == 'colab' and cwd.parent.name == 'notebooks':\n",
            "        REPO_DIR = cwd.parents[1]\n",
            "    # Caso 2: notebook aberto em ai-core/notebooks\n",
            "    elif cwd.name == 'notebooks':\n",
            "        REPO_DIR = cwd.parent\n",
            "    # Caso 3: notebook aberto já na raiz ai-core\n",
            "    else:\n",
            "        REPO_DIR = cwd\n",
            "\n",
            "SRC_PATH = REPO_DIR / 'src'\n",
            "if str(SRC_PATH) not in sys.path:\n",
            "    sys.path.insert(0, str(SRC_PATH))\n",
            "\n",
            "print('IN_COLAB:', IN_COLAB)\n",
            "print('CWD:', Path.cwd().resolve())\n",
            "print('REPO_DIR:', REPO_DIR)\n",
            "print('SRC_PATH:', SRC_PATH)\n",
            "print('scripts exists:', (REPO_DIR / 'scripts').exists())\n",
            "print('src exists:', SRC_PATH.exists())\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Etapa 2 — Dados e integração com Google Drive\n",
            "\n",
            "Esta etapa prepara o acesso aos dados.\n",
            "\n",
            "### Comportamento esperado\n",
            "- no Colab: monta o Google Drive e permite copiar dados de `MyDrive/data/`\n",
            "- no local: apenas valida se os artefatos esperados já existem em `data/`\n",
            "\n",
            "### Estrutura esperada dos dados no Drive\n",
            "```text\n",
            "MyDrive/data/\n",
            "  raw/\n",
            "  processed/\n",
            "```\n",
            "\n",
            "### Observação\n",
            "As linhas de cópia ficam comentadas por padrão para evitar operações desnecessárias.\n",
            "Descomente apenas se quiser copiar os dados do Drive para dentro do diretório do projeto no Colab.\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from pathlib import Path\n",
            "import shutil\n",
            "\n",
            "if IN_COLAB:\n",
            "    try:\n",
            "        from google.colab import drive\n",
            "        drive.mount('/content/drive')\n",
            "    except Exception as e:\n",
            "        print('Drive mount opcional:', e)\n",
            "\n",
            "PROJECT_ROOT = REPO_DIR\n",
            "DATA_TARGET = PROJECT_ROOT / 'data'\n",
            "DATA_TARGET.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "SOURCE_RAW_DIR = Path('/content/drive/MyDrive/data/raw')\n",
            "SOURCE_PROCESSED_DIR = Path('/content/drive/MyDrive/data/processed')\n",
            "\n",
            "# Descomente se quiser copiar do Drive no Colab:\n",
            "# shutil.copytree(SOURCE_RAW_DIR, DATA_TARGET / 'raw', dirs_exist_ok=True)\n",
            "# shutil.copytree(SOURCE_PROCESSED_DIR, DATA_TARGET / 'processed', dirs_exist_ok=True)\n",
            "\n",
            "for p in [\n",
            "    REPO_DIR / 'data' / 'raw' / 'answers.json',\n",
            "    REPO_DIR / 'data' / 'processed' / 'sequences' / 'user_sequences.json',\n",
            "]:\n",
            "    print(p, p.exists())\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Etapa 3 — Regenerar artefatos base (opcional)\n",
            "\n",
            "Use esta etapa se você ainda não possui os artefatos processados ou se quiser reconstruir tudo.\n",
            "\n",
            "### O que pode ser regenerado\n",
            "- `answers_prepared.csv`\n",
            "- `user_sequences.json`\n",
            "- mapeamentos H2/H3\n",
            "- sequências por sessão\n",
            "\n",
            "Por padrão, esta célula fica comentada para evitar reprocessamentos desnecessários.\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Opcional: regenere os artefatos base e sequências por sessão.\n",
            "# get_ipython().system('python run_data_pipeline.py')\n",
            "# get_ipython().system('python scripts/build_user_session_sequences.py')\n",
        ],
    },
]

RUN_AND_PLOT = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Etapa 4 — Executar o treino do experimento\n",
            "\n",
            "Nesta etapa, o notebook roda o script oficial do experimento correspondente.\n",
            "\n",
            "### O que acontece aqui\n",
            "- o script é executado dentro da raiz do projeto,\n",
            "- o `PYTHONPATH` é ajustado para usar `src/`,\n",
            "- o stdout do treino é capturado,\n",
            "- o notebook tenta extrair automaticamente o histórico de epochs a partir dos logs impressos.\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import subprocess\n",
            "import re\n",
            "import json\n",
            "from pathlib import Path\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "SCRIPT_PATH = '{SCRIPT_PATH}'\n",
            "SUMMARY_NAME = '{SUMMARY_NAME}'\n",
            "\n",
            "cmd = f'PYTHONPATH=./src python {SCRIPT_PATH}'\n",
            "print('Running:', cmd)\n",
            "\n",
            "result = subprocess.run(\n",
            "    cmd,\n",
            "    shell=True,\n",
            "    cwd=REPO_DIR,\n",
            "    capture_output=True,\n",
            "    text=True,\n",
            ")\n",
            "\n",
            "print(result.stdout)\n",
            "if result.returncode != 0:\n",
            "    print(result.stderr)\n",
            "    raise RuntimeError(f'Command failed with code {result.returncode}')\n",
            "\n",
            "pattern = re.compile(\n",
            "    r'Epoch\\s+(\\d+)(?:/(\\d+))?\\s*\\|\\s*'\n",
            "    r'Train Loss:\\s*([0-9.]+)'\n",
            "    r'(?:\\s*\\|\\s*Train AUC:\\s*([0-9.]+))?'\n",
            "    r'\\s*\\|\\s*Val Loss:\\s*([0-9.]+)'\n",
            "    r'\\s*\\|\\s*Val AUC:\\s*([0-9.]+)'\n",
            "    r'\\s*\\|\\s*Val Acc:\\s*([0-9.]+)'\n",
            "    r'\\s*\\|\\s*LR:\\s*([0-9.eE+-]+)'\n",
            ")\n",
            "\n",
            "rows = []\n",
            "for line in result.stdout.splitlines():\n",
            "    m = pattern.search(line)\n",
            "    if m:\n",
            "        rows.append(\n",
            "            {\n",
            "                'epoch': int(m.group(1)),\n",
            "                'train_loss': float(m.group(3)),\n",
            "                'train_auc': float(m.group(4)) if m.group(4) else None,\n",
            "                'val_loss': float(m.group(5)),\n",
            "                'val_auc': float(m.group(6)),\n",
            "                'val_acc': float(m.group(7)),\n",
            "                'lr': float(m.group(8)),\n",
            "            }\n",
            "        )\n",
            "\n",
            "history_df = pd.DataFrame(rows)\n",
            "history_df\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Etapa 5 — Visualizar curvas de Loss e AUC\n",
            "\n",
            "Esses gráficos servem para diagnosticar o comportamento do treino.\n",
            "\n",
            "### O que observar\n",
            "- **Train Loss ↓ e Val Loss ↑**: possível overfitting\n",
            "- **Val AUC subindo**: o modelo está generalizando melhor\n",
            "- **Val AUC estabilizada/caindo**: o modelo pode ter atingido o limite ou começado a overfitar\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig = plt.figure(figsize=(10, 5))\n",
            "plt.plot(history_df['epoch'], history_df['train_loss'], label='Train Loss')\n",
            "plt.plot(history_df['epoch'], history_df['val_loss'], label='Val Loss')\n",
            "plt.title(SUMMARY_NAME + ' - Loss')\n",
            "plt.xlabel('Epoch')\n",
            "plt.ylabel('Loss')\n",
            "plt.legend()\n",
            "plt.grid(alpha=0.3)\n",
            "plt.show()\n",
            "\n",
            "if history_df['train_auc'].notna().any():\n",
            "    fig = plt.figure(figsize=(10, 5))\n",
            "    plt.plot(history_df['epoch'], history_df['train_auc'], label='Train AUC')\n",
            "    plt.plot(history_df['epoch'], history_df['val_auc'], label='Val AUC')\n",
            "    plt.title(SUMMARY_NAME + ' - AUC')\n",
            "    plt.xlabel('Epoch')\n",
            "    plt.ylabel('AUC')\n",
            "    plt.legend()\n",
            "    plt.grid(alpha=0.3)\n",
            "    plt.show()\n",
        ],
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Etapa 6 — Ler métricas finais e salvar resumo consolidado\n",
            "\n",
            "Nesta etapa, o notebook tenta localizar o diretório do run salvo pelo script oficial,\n",
            "carrega o `metrics.json` e salva um resumo padronizado em:\n",
            "\n",
            "```text\n",
            "artifacts/colab_summaries/\n",
            "```\n",
            "\n",
            "Isso permite comparar todos os experimentos depois em um único notebook.\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "saved_match = re.search(r'Saved run to\\s+(.+)', result.stdout)\n",
            "run_dir = Path(saved_match.group(1).strip()) if saved_match else None\n",
            "\n",
            "metrics = {}\n",
            "if run_dir and (run_dir / 'metrics.json').exists():\n",
            "    metrics = json.loads((run_dir / 'metrics.json').read_text())\n",
            "\n",
            "metrics\n",
            "\n",
            "summary_dir = Path('artifacts/colab_summaries')\n",
            "summary_dir.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            "(summary_dir / f'{SUMMARY_NAME}_history.csv').write_text(history_df.to_csv(index=False))\n",
            "(summary_dir / f'{SUMMARY_NAME}_metrics.json').write_text(json.dumps(metrics, indent=2))\n",
            "\n",
            "print('Saved summary files to', summary_dir)\n",
        ],
    },
]

TASKS = [
    (
        "01_dkt_next_item_colab.ipynb",
        "DKT Next-Item",
        "scripts/train_eval_dkt_next_item.py",
        "dkt_next_item",
    ),
    ("02_dkt_h2_colab.ipynb", "DKT H2", "scripts/train_eval_dkt_topic_h2.py", "dkt_h2"),
    ("03_dkt_h3_colab.ipynb", "DKT H3", "scripts/train_eval_dkt_topic_h3.py", "dkt_h3"),
    (
        "04_lpkt_next_item_colab.ipynb",
        "LPKT Next-Item",
        "scripts/train_eval_lpkt_next_item.py",
        "lpkt_next_item",
    ),
    (
        "05_lpkt_h2_colab.ipynb",
        "LPKT H2",
        "scripts/train_eval_lpkt_topic_h2.py",
        "lpkt_h2",
    ),
    (
        "06_lpkt_h3_colab.ipynb",
        "LPKT H3",
        "scripts/train_eval_lpkt_topic_h3.py",
        "lpkt_h3",
    ),
    (
        "07_dkvmn_next_item_colab.ipynb",
        "DKVMN Next-Item",
        "scripts/train_eval_dkvmn_next_item.py",
        "dkvmn_next_item",
    ),
    (
        "08_dkvmn_h2_colab.ipynb",
        "DKVMN H2",
        "scripts/train_eval_dkvmn_topic_h2.py",
        "dkvmn_h2",
    ),
    (
        "09_dkvmn_h3_colab.ipynb",
        "DKVMN H3",
        "scripts/train_eval_dkvmn_topic_h3.py",
        "dkvmn_h3",
    ),
]


def replace(obj, title: str, script: str, summary: str):
    if isinstance(obj, str):
        return (
            obj.replace("{TITLE}", title)
            .replace("{SCRIPT_PATH}", script)
            .replace("{SUMMARY_NAME}", summary)
        )
    if isinstance(obj, list):
        return [replace(x, title, script, summary) for x in obj]
    if isinstance(obj, dict):
        return {k: replace(v, title, script, summary) for k, v in obj.items()}
    return obj


# ============================================================
# Geração dos 9 notebooks de treino
# ============================================================

for filename, title, script, summary in TASKS:
    cells = replace(COMMON_SETUP + RUN_AND_PLOT, title, script, summary)
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    (OUT / filename).write_text(json.dumps(nb, ensure_ascii=False))


# ============================================================
# Notebook comparativo
# ============================================================

compare_nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Compare all KT runs\n",
                "\n",
                "Este notebook lê os resultados padronizados salvos em `artifacts/colab_summaries/`\n",
                "e compara as métricas dos 9 experimentos.\n",
                "\n",
                "## Objetivo\n",
                "Permitir uma visão consolidada de:\n",
                "- AUC de validação e teste\n",
                "- Loss de validação e teste\n",
                "- Accuracy de teste\n",
                "- diferenças entre modelos e tarefas\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 1 — Setup e localização do diretório de summaries\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from pathlib import Path\n",
                "import json\n",
                "import sys\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "IN_COLAB = 'google.colab' in sys.modules\n",
                "REPO_URL = 'https://github.com/GuilhermeDesoler/ai-core.git'\n",
                "\n",
                "if IN_COLAB:\n",
                "    REPO_DIR = Path('/content/ai-core')\n",
                "    if not REPO_DIR.exists():\n",
                "        get_ipython().system(f'git clone -b improve/high-impact-training {REPO_URL} /content/ai-core')\n",
                "    get_ipython().run_line_magic('cd', '/content/ai-core')\n",
                "    get_ipython().system('pip install -q -r requirements.txt')\n",
                "else:\n",
                "    cwd = Path.cwd().resolve()\n",
                "    if cwd.name == 'colab' and cwd.parent.name == 'notebooks':\n",
                "        REPO_DIR = cwd.parents[1]\n",
                "    elif cwd.name == 'notebooks':\n",
                "        REPO_DIR = cwd.parent\n",
                "    else:\n",
                "        REPO_DIR = cwd\n",
                "\n",
                "summary_dir = REPO_DIR / 'artifacts' / 'colab_summaries'\n",
                "print('Summary dir:', summary_dir)\n",
                "print('Exists:', summary_dir.exists())\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 2 — Carregar métricas consolidadas\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "rows = []\n",
                "for p in sorted(summary_dir.glob('*_metrics.json')):\n",
                "    data = json.loads(p.read_text()) if p.exists() else {}\n",
                "    name = p.stem.replace('_metrics', '')\n",
                "    model, task = name.split('_', 1)\n",
                "    rows.append(\n",
                "        {\n",
                "            'name': name,\n",
                "            'model': model.upper(),\n",
                "            'task': task,\n",
                "            'best_val_auc': data.get('best_val_auc'),\n",
                "            'best_val_loss': data.get('best_val_loss'),\n",
                "            'test_auc': data.get('test_auc'),\n",
                "            'test_loss': data.get('test_loss'),\n",
                "            'test_acc': data.get('test_acc'),\n",
                "        }\n",
                "    )\n",
                "\n",
                "results_df = pd.DataFrame(rows).sort_values(['task', 'model'])\n",
                "results_df\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 3 — Comparar métricas com tabelas e gráficos\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "for metric in ['test_auc', 'test_loss', 'test_acc']:\n",
                "    pivot = results_df.pivot(index='task', columns='model', values=metric)\n",
                "    display(pivot)\n",
                "    fig = plt.figure(figsize=(10, 5))\n",
                "    pivot.plot(kind='bar', ax=plt.gca())\n",
                "    plt.title(f'Comparison - {metric}')\n",
                "    plt.ylabel(metric)\n",
                "    plt.grid(alpha=0.3)\n",
                "    plt.show()\n",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
(OUT / "10_compare_all_models_colab.ipynb").write_text(
    json.dumps(compare_nb, ensure_ascii=False)
)


# ============================================================
# Notebook de EDA forte
# ============================================================

eda_nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# EDA full analysis for KT\n",
                "\n",
                "Análise exploratória forte focada em:\n",
                "- qualidade do dado,\n",
                "- tamanho das sequências,\n",
                "- intervalos temporais,\n",
                "- sessões,\n",
                "- fragmentação de estudo,\n",
                "- repetição por skill,\n",
                "- adequação do dado para KT / LPKT / DKVMN.\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 1 — Setup e carregamento dos dados\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from pathlib import Path\n",
                "import json\n",
                "import sys\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "IN_COLAB = 'google.colab' in sys.modules\n",
                "REPO_URL = 'https://github.com/GuilhermeDesoler/ai-core.git'\n",
                "\n",
                "if IN_COLAB:\n",
                "    REPO_DIR = Path('/content/ai-core')\n",
                "    if not REPO_DIR.exists():\n",
                "        get_ipython().system(f'git clone -b improve/high-impact-training {REPO_URL} /content/ai-core')\n",
                "    get_ipython().run_line_magic('cd', '/content/ai-core')\n",
                "    get_ipython().system('pip install -q -r requirements.txt')\n",
                "else:\n",
                "    cwd = Path.cwd().resolve()\n",
                "    if cwd.name == 'colab' and cwd.parent.name == 'notebooks':\n",
                "        REPO_DIR = cwd.parents[1]\n",
                "    elif cwd.name == 'notebooks':\n",
                "        REPO_DIR = cwd.parent\n",
                "    else:\n",
                "        REPO_DIR = cwd\n",
                "\n",
                "answers = pd.read_csv(REPO_DIR / 'data' / 'processed' / 'dataset' / 'answers_prepared.csv')\n",
                "with open(REPO_DIR / 'data' / 'processed' / 'sequences' / 'user_sequences.json') as f:\n",
                "    sequences = json.load(f)\n",
                "\n",
                "answers['timestamp_dt'] = pd.to_datetime(answers['timestamp'], unit='ms', errors='coerce')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 2 — Visão geral do dataset\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "overview = pd.Series(\n",
                "    {\n",
                "        'rows': len(answers),\n",
                "        'users': answers['user_id'].nunique(),\n",
                "        'questions': answers['question_id'].nunique(),\n",
                "        'skills': answers['skill_id'].nunique(),\n",
                "        'correct_rate': float(answers['correct'].mean()),\n",
                "        'dup_rows': int(answers.duplicated().sum()),\n",
                "        'time_zero_rate': float((answers['time_response'] == 0).mean()),\n",
                "    }\n",
                ")\n",
                "overview.to_frame('value')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 3 — Interações por usuário\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "user_stats = answers.groupby('user_id').agg(\n",
                "    n_interactions=('question_id', 'size'),\n",
                "    n_skills=('skill_id', 'nunique'),\n",
                "    first_ts=('timestamp_dt', 'min'),\n",
                "    last_ts=('timestamp_dt', 'max'),\n",
                ").reset_index()\n",
                "\n",
                "user_stats['timespan_hours'] = ((user_stats['last_ts'] - user_stats['first_ts']).dt.total_seconds() / 3600).fillna(0)\n",
                "\n",
                "display(user_stats[['n_interactions', 'n_skills', 'timespan_hours']].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]))\n",
                "\n",
                "fig = plt.figure(figsize=(10, 5))\n",
                "plt.hist(user_stats['n_interactions'], bins=50)\n",
                "plt.title('Interactions per user')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 4 — Intervalos de tempo\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "answers = answers.sort_values(['user_id', 'timestamp']).copy()\n",
                "answers['delta_t_ms'] = answers.groupby('user_id')['timestamp'].diff().fillna(0)\n",
                "answers['delta_t_min'] = answers['delta_t_ms'] / 60000\n",
                "\n",
                "display(\n",
                "    pd.Series(\n",
                "        {\n",
                "            'delta_p50_min': float(answers['delta_t_min'].quantile(0.5)),\n",
                "            'delta_p90_min': float(answers['delta_t_min'].quantile(0.9)),\n",
                "            'delta_p99_min': float(answers['delta_t_min'].quantile(0.99)),\n",
                "            'time_p99_sec': float(answers['time_response'].quantile(0.99) / 1000),\n",
                "        }\n",
                "    ).to_frame('value')\n",
                ")\n",
                "\n",
                "fig = plt.figure(figsize=(10, 5))\n",
                "plt.hist(np.log1p(answers['delta_t_ms']), bins=60)\n",
                "plt.title('log1p(delta_t_ms)')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 5 — Sessões\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "SESSION_GAP_MIN = 60\n",
                "\n",
                "answers['new_session_flag'] = (\n",
                "    (answers['delta_t_min'] > SESSION_GAP_MIN)\n",
                "    | (answers.groupby('user_id').cumcount() == 0)\n",
                ").astype(int)\n",
                "\n",
                "answers['session_idx'] = answers.groupby('user_id')['new_session_flag'].cumsum()\n",
                "\n",
                "session_stats = answers.groupby(['user_id', 'session_idx']).agg(\n",
                "    n_interactions=('question_id', 'size'),\n",
                "    n_skills=('skill_id', 'nunique'),\n",
                ").reset_index()\n",
                "\n",
                "display(session_stats[['n_interactions', 'n_skills']].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]))\n",
                "\n",
                "fig = plt.figure(figsize=(10, 5))\n",
                "plt.hist(session_stats['n_interactions'], bins=40)\n",
                "plt.title('Session length')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 6 — Fragmentação de estudo\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "answers['prev_skill_id'] = answers.groupby('user_id')['skill_id'].shift(1)\n",
                "answers['skill_switch'] = (\n",
                "    (answers['prev_skill_id'].notna())\n",
                "    & (answers['skill_id'] != answers['prev_skill_id'])\n",
                ").astype(int)\n",
                "\n",
                "frag = answers.groupby('user_id').agg(\n",
                "    n_interactions=('question_id', 'size'),\n",
                "    n_skills=('skill_id', 'nunique'),\n",
                "    switches=('skill_switch', 'sum'),\n",
                ").reset_index()\n",
                "\n",
                "frag['switch_rate'] = frag['switches'] / (frag['n_interactions'] - 1).clip(lower=1)\n",
                "frag['interactions_per_skill'] = frag['n_interactions'] / frag['n_skills'].clip(lower=1)\n",
                "\n",
                "display(frag[['switch_rate', 'interactions_per_skill']].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]))\n",
                "\n",
                "fig = plt.figure(figsize=(10, 5))\n",
                "plt.hist(frag['switch_rate'], bins=40)\n",
                "plt.title('Skill switch rate')\n",
                "plt.show()\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 7 — Repetição por skill\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "user_skill_counts = answers.groupby(['user_id', 'skill_id']).size().reset_index(name='n_attempts')\n",
                "\n",
                "repeat_summary = pd.Series(\n",
                "    {\n",
                "        'mean_attempts_per_user_skill': float(user_skill_counts['n_attempts'].mean()),\n",
                "        'median_attempts_per_user_skill': float(user_skill_counts['n_attempts'].median()),\n",
                "        'share_attempted_once': float((user_skill_counts['n_attempts'] == 1).mean()),\n",
                "        'share_attempted_ge_3': float((user_skill_counts['n_attempts'] >= 3).mean()),\n",
                "    }\n",
                ")\n",
                "repeat_summary.to_frame('value')\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Etapa 8 — Diagnóstico de adequação para KT\n"],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "diagnostic = pd.DataFrame(\n",
                "    [\n",
                "        {\n",
                "            'criterion': 'long user histories',\n",
                "            'value': float(user_stats['n_interactions'].median()),\n",
                "            'comment': 'higher is better for KT',\n",
                "        },\n",
                "        {\n",
                "            'criterion': 'session length',\n",
                "            'value': float(session_stats['n_interactions'].median()),\n",
                "            'comment': 'short sessions hurt temporal KT',\n",
                "        },\n",
                "        {\n",
                "            'criterion': 'skill switch rate',\n",
                "            'value': float(frag['switch_rate'].median()),\n",
                "            'comment': 'high values mean fragmented study',\n",
                "        },\n",
                "        {\n",
                "            'criterion': 'repeat per user-skill >= 3',\n",
                "            'value': float((user_skill_counts['n_attempts'] >= 3).mean()),\n",
                "            'comment': 'higher helps mastery modeling',\n",
                "        },\n",
                "        {\n",
                "            'criterion': 'time_response zero rate',\n",
                "            'value': float((answers['time_response'] == 0).mean()),\n",
                "            'comment': 'high values reduce temporal signal',\n",
                "        },\n",
                "    ]\n",
                ")\n",
                "diagnostic\n",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
(OUT / "11_eda_full_analysis_colab.ipynb").write_text(
    json.dumps(eda_nb, ensure_ascii=False)
)

print("Generated notebooks in", OUT)
for p in sorted(OUT.glob("*.ipynb")):
    print("-", p.name)
